### ISSUE TITLE
Some programs do not create a start menu entry

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#334]
http://files.mpoli.fi/software/WIN16/UTILS/MISC/SMTACC.ZIP
http://files.mpoli.fi/software/WIN16/UTILS/MISC/HP12C12.ZIP

**Fixed:**
http://files.mpoli.fi/software/WIN16/EDITORS/WXPRS.ZIP
http://files.mpoli.fi/software/WIN16/GRAPHICS/PSP311.ZIP
http://files.mpoli.fi/software/WIN16/UTILS/MISC/SKYMAP.ZIP

**Comment by cracyc** [comment]
I installed word express to test and it created an icon properly.

**Comment by Anixx** [comment]
It does not on my system.

**Comment by cracyc** [comment]
https://github.com/otya128/winevdm/pull/343 may fix it for you

**Comment by Anixx** [comment]
Word Express now creates the icon, but HP12C12 and Skymap do not.

**Comment by cracyc** [comment]
Skymap uses FindWindow("PROGMAN") to get the window handle to send dde commands too.  That doesn't work right now.

**Comment by Anixx** [comment]
HP12C12 still does not create a group, and its installer hangs without exit after saying installation complete.

**Comment by Anixx** [comment]
Smart Accounts now creates the program group, but it is empty.

**Comment by Anixx** [comment]
Also, creates some strange window looking like this:
![Clipboard_20190601](https://user-images.githubusercontent.com/1271736/58745844-41127900-845f-11e9-93ca-fe94e10bb8a9.png)
which does not exit after installation.

**Comment by Anixx** [comment]
Skymap is fixed.

**Comment by cracyc** [comment]
> HP12C12 still does not create a group, and its installer segfaults after saying installation complete.

Segfault is fixed in https://github.com/otya128/winevdm/pull/369 but this is complex.  It does async dde which expects an HGLOBAL  with XTYP_EXECUTE so XTYP_XACT_COMPLETE can then be sent.  First, it uses GETKBCODEPAGE to get the dde codepage which isn't CP_WINANSI so that fails.  If that's fixed then in convert_handle_32_to_16 and convert_handle_16_to_32 convert the HGLOBAL to an HGLOBAL16 then back to a different HGLOBAL which causes ddeml to fail to send the XTYP_XACT_COMPLETE.

**Comment by cracyc** [comment]
> Also, creates some strange window looking like this:
> ![Clipboard_20190601](https://user-images.githubusercontent.com/1271736/58745844-41127900-845f-11e9-93ca-fe94e10bb8a9.png)
> which does not exit after installation.

The window is hidden but the process still doesn't exit.  The installer has a stub which runs first then should exit and clean up but it hangs on WaitMessage and when it gets any message it checks if the installer is done but since it has no window it never gets any messages and so waits forever.
