### ISSUE TITLE
Superbase does not start: shows splash screen and exits

### ISSUE THREAD

**Issue by Anixx** [otya128/winevdm#351]
https://winworldpc.com/download/e2809d0a-e280-a6c3-9542-c38111c3a7ef/from/71c2ad43-2482-11e8-a4ce-fa163e9022f0

**Comment by cracyc** [comment]
This problem is fixed by https://github.com/otya128/winevdm/pull/349.  This also will show "Insufficient memory" if the printer name is too long.

```
1ca4:Call WINSPOOL.90: EXTDEVICEMODE(0025,16e7,0000:0000,15e77986 "\\\\http://*redacted*:631\\Brother_HL",15e742c8 "Ne03:",0000:0000,00000000 (null),0000) ret=1417:1532 ds=15e7
1ca4:Ret  WINSPOOL.90: EXTDEVICEMODE() retval=ffffffff ret=1417:1532 ds=15e7
1ca4:Call KERNEL.15: GLOBALALLOC(0002,ffffffff) ret=122f:0574 ds=15e7
     AX=15e7 BX=000e CX=0000 DX=ffff SI=02af DI=78d4 ES=15e7 EFL=00003292
1ca4:err:global:GlobalAlloc16 328: Could not allocate 0002,FFFFFFFF
1ca4:Ret  KERNEL.15: GLOBALALLOC() retval=none ret=122f:0574 ds=15e7
     AX=0000 BX=0000 CX=0000 DX=ffff SI=02af DI=78d4 ES=0000 EFL=00003292
```
The printer name is cut off so EXTDEVICEMODE returns -1 (which doesn't appear to be documented) and it tries to allocate 4GB.

**Comment by WINEVDMbetaTester** [comment]
This problem is still happening, I have done new tests with the new version 1309

with Superbase 95, Superbase 2001 and super base clasic 2003

**Comment by cracyc** [comment]
Now that the commit has been pulled, try again.

**Comment by WINEVDMbetaTester** [comment]
I've tried it again with the dev1313. and those versions still close after showing the home screen.

**Comment by cracyc** [comment]
Superbase 95 works fine for me.

**Comment by WINEVDMbetaTester** [comment]
Will it have something to do with the amount of ram I have on my computer?

I have only 4 GB

I also have the same problem with programs like approach or perfect office.

**Comment by Anixx** [comment]
Still exits after showing the splash screen.

**Comment by cracyc** [comment]
>Will it have something to do with the amount of ram I have on my computer?

Doubt it.  Probably need a trace to get any idea of why.

**Comment by Anixx** [comment]
Now it says "insufficient memory" before exitting.

**Comment by Anixx** [comment]
Still, "insufficient memory".
