### ISSUE TITLE
Notabene 9, further error message

### ISSUE THREAD

**Issue by PBreeze** [otya128/winevdm#585]
Try the latest version first.
Go [here](https://ci.appveyor.com/project/otya128/winevdm) and click `Environment: THIS_BUILD_IS_RECOMMENDED__VCXPROJ_BUILD=1`-> `Artifacts 1`-> `zip` to download the latest version.

Builds 1597 and 1599 has made some progress.  However on trying to run Notabene 9 I how get another error message as shown in the screen capture below:

![nb error 2](https://user-images.githubusercontent.com/59335560/72064998-116cfe80-32d5-11ea-9053-c275575eba10.jpg)

I have added a further trace at the bottom.
**Describe the bug**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Windows 10 1903]
 - Version [e.g. version: 1523]

Windows 7 64 bit

**Additional context**

It is very helpful to provide a trace file if possible.
Please note that this file contains detailed information about the program.
**Procedure**
1. Run the command prompt.
2. Set the environment variable:
```cmd
set WINEDEBUG=+all,-snoop,-ldt,-fixup,-module,-global,-local,-disasm,-syslevel,-thunk
```
3.
```cmd
*old-executable-file* 2> trace.txt
```
4. Upload trace.txt here.
The trace below was made with build 1597:
[trace.txt](https://github.com/otya128/winevdm/files/4040195/trace.txt)

The trace below was made with build 1599, which I missed first time around:
[trace.txt](https://github.com/otya128/winevdm/files/4040226/trace.txt)
However I think the traces are identical

**Comment by cracyc** [comment]
It looks like psa->pvdata in SafeArrayRedim16 is a segptr so it can't be passed to memcpy at https://github.com/otya128/winevdm/blob/b934f7f14add0fb658ac92168e82621a323328e1/ole2disp/ole2disp.c#L538 without calling MapSL first.  I could be missing something though so @otya128 ought to look at it.

**Comment by cracyc** [comment]
I was able to repo the error in vb4 and https://github.com/otya128/winevdm/pull/586 should fix it

**Comment by PBreeze** [comment]
I have installed 1602 but I still get a very similar error (though not exactly identical)

![NB error 3](https://user-images.githubusercontent.com/59335560/72156861-7183a380-33ae-11ea-96cb-d387983d32b0.jpg)

The trace for this is below:

[trace.txt](https://github.com/otya128/winevdm/files/4045822/trace.txt)

Notabene released this particular 16 bit version of the word processor in 2010 so they may well have pushed the use of 16 bit to the limit.

Thanks for your help with this.

**Comment by cracyc** [comment]
1602 doesn't include the fix, you need 1601 https://ci.appveyor.com/project/otya128/winevdm/builds/30014218

**Comment by PBreeze** [comment]
OK, I have 1601 now and it shows signs of progress.  The loading gets as far as the splash screen now which it did not before.  Then the following error message appears

![nb error 4](https://user-images.githubusercontent.com/59335560/72169272-b0bdee80-33c6-11ea-90bf-60ad636f4f81.jpg)

If I select continue then I get the second error box, below:

![nb error 5](https://user-images.githubusercontent.com/59335560/72169311-c4695500-33c6-11ea-965b-5577f9ea47bc.jpg)

Selecting cancel at this stage provides the following trace - which has grown alarmingly since last time:

[trace.txt](https://github.com/otya128/winevdm/files/4046624/trace.txt)

**Comment by cracyc** [comment]
https://ci.appveyor.com/project/otya128/winevdm/builds/30049519/job/c4x24kgc09cyitax/artifacts should fix the next errors

**Comment by PBreeze** [comment]
This has eliminated the SEGV error.  Now I get the error message below:

![nd error 6](https://user-images.githubusercontent.com/59335560/72218788-d8cc5f80-3536-11ea-9da8-484bc2bc2fb3.jpg)

The new trace is below:

[trace.txt](https://github.com/otya128/winevdm/files/4050641/trace.txt)

The program terminated itself without me needing to press either retry or cancel.

**Comment by cracyc** [comment]
try https://ci.appveyor.com/project/otya128/winevdm/builds/30060510/job/ma8ij8xxxak60rg5/artifacts

**Comment by PBreeze** [comment]
With 1607 I get a new SEGV error, shown below:

![nb error 7](https://user-images.githubusercontent.com/59335560/72258691-9e31f800-3606-11ea-8d75-95c2e692783c.jpg)

If I select continue, then for the first time a notabene window opens, but with a second SEGV error, below

![nb error 8](https://user-images.githubusercontent.com/59335560/72258734-b73aa900-3606-11ea-85fb-6f66a4d2bcec.jpg)

I have run a trace for this, but the behaviour when running the trace is not exactly the same as the second stage does not appear -- or at least it is there somewhere but I cannot make it appear on the screen.  However I think it has probably proceeded to virtually the same stage

[trace.txt](https://github.com/otya128/winevdm/files/4053685/trace.txt)

**Comment by cracyc** [comment]
The trace crash is fixed in https://ci.appveyor.com/project/otya128/winevdm/builds/30076370/job/6a6qdkgi4m6gcccl/artifacts

**Comment by PBreeze** [comment]
With 1609, Notabene 9 completes the startup process and launches correctly.  There is a curious pause just before the end of the startup with the eggtimer cursor on screen for half a minute or more.  I have run a trace for the startup but when running the trace, the startup never completes and the trace file just grows and grows.   The smallest one I can achieve is 38M which is too big to load in GitHub.  (One reached 130M before I stopped the process.)

Looking into the trace, it seems to be a repeating loop at the end.  I have lopped off the last 250k which is loaded below:

[trace.txt](https://github.com/otya128/winevdm/files/4059085/trace.txt)


I have also encountered and error when running a routine within Notabene 9 . This triggers a "Windows Explorer has stopped working" error message with the option to restart it.   However selecting this just sends it in a loop with the error box appearing again.  On the other hand ending the routine inside Notabene 9 stops this looping.  Is there any way of catching this error by running a trace after the program has started?

**Comment by PBreeze** [comment]
Further to the above, I am getting an error box when I try to open some files.  See below:

![nb error 9](https://user-images.githubusercontent.com/59335560/72345578-0696dd00-36cc-11ea-8342-e3b7da619def.jpg)

This is a file that would normally open in the program.

**Comment by cracyc** [comment]
There's not enough info to debug these without direct access to the program.  Looks like there was a demo available for the program but that's long gone.

**Comment by PBreeze** [comment]
I have a copy of the trial version but it is 24MB so I cannot upload it to github.  You could try downloading from here:

https://download.freedownloadmanager.org/Windows-PC/Nota-Bene/FREE.html

If not I could send you a copy privately.
